/* tslint:disable */
/* eslint-disable */
/**
 * Kallipr.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CustomerDto
 */
export interface CustomerDto {
    /**
     * 
     * @type {string}
     * @memberof CustomerDto
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerDto
     */
    'name'?: string | null;
}
/**
 * 
 * @export
 * @interface DeviceDto
 */
export interface DeviceDto {
    /**
     * 
     * @type {string}
     * @memberof DeviceDto
     */
    'customerId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceDto
     */
    'deviceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceDto
     */
    'label'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceDto
     */
    'location'?: string | null;
}
/**
 * 
 * @export
 * @interface TelemetryEventDto
 */
export interface TelemetryEventDto {
    /**
     * 
     * @type {number}
     * @memberof TelemetryEventDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TelemetryEventDto
     */
    'customerId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TelemetryEventDto
     */
    'deviceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TelemetryEventDto
     */
    'eventId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TelemetryEventDto
     */
    'recordedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TelemetryEventDto
     */
    'type'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TelemetryEventDto
     */
    'value'?: number;
    /**
     * 
     * @type {string}
     * @memberof TelemetryEventDto
     */
    'unit'?: string | null;
}
/**
 * 
 * @export
 * @interface TelemetryEventsWindowInsightsDto
 */
export interface TelemetryEventsWindowInsightsDto {
    /**
     * 
     * @type {number}
     * @memberof TelemetryEventsWindowInsightsDto
     */
    'latestValue'?: number;
    /**
     * 
     * @type {number}
     * @memberof TelemetryEventsWindowInsightsDto
     */
    'minimumValue'?: number;
    /**
     * 
     * @type {number}
     * @memberof TelemetryEventsWindowInsightsDto
     */
    'maximumValue'?: number;
    /**
     * 
     * @type {number}
     * @memberof TelemetryEventsWindowInsightsDto
     */
    'averageValue'?: number;
}

/**
 * CustomerApi - axios parameter creator
 * @export
 */
export const CustomerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCustomers: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Customer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CustomerApi - functional programming interface
 * @export
 */
export const CustomerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CustomerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCustomers(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CustomerDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCustomers(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CustomerApi.listCustomers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CustomerApi - factory interface
 * @export
 */
export const CustomerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CustomerApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCustomers(options?: RawAxiosRequestConfig): AxiosPromise<Array<CustomerDto>> {
            return localVarFp.listCustomers(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CustomerApi - object-oriented interface
 * @export
 * @class CustomerApi
 * @extends {BaseAPI}
 */
export class CustomerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomerApi
     */
    public listCustomers(options?: RawAxiosRequestConfig) {
        return CustomerApiFp(this.configuration).listCustomers(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DeviceApi - axios parameter creator
 * @export
 */
export const DeviceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} deviceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTelemetryEventsWindowInsights: async (deviceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceId' is not null or undefined
            assertParamExists('getTelemetryEventsWindowInsights', 'deviceId', deviceId)
            const localVarPath = `/Device/{deviceId}/TelemetryEventsWindowInsights`
                .replace(`{${"deviceId"}}`, encodeURIComponent(String(deviceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDevices: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Device`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} deviceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTelemetryEvents: async (deviceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceId' is not null or undefined
            assertParamExists('listTelemetryEvents', 'deviceId', deviceId)
            const localVarPath = `/Device/{deviceId}/TelemetryEvents`
                .replace(`{${"deviceId"}}`, encodeURIComponent(String(deviceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeviceApi - functional programming interface
 * @export
 */
export const DeviceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DeviceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} deviceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTelemetryEventsWindowInsights(deviceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TelemetryEventsWindowInsightsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTelemetryEventsWindowInsights(deviceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceApi.getTelemetryEventsWindowInsights']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDevices(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DeviceDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDevices(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceApi.listDevices']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} deviceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTelemetryEvents(deviceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TelemetryEventDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTelemetryEvents(deviceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceApi.listTelemetryEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DeviceApi - factory interface
 * @export
 */
export const DeviceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DeviceApiFp(configuration)
    return {
        /**
         * 
         * @param {DeviceApiGetTelemetryEventsWindowInsightsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTelemetryEventsWindowInsights(requestParameters: DeviceApiGetTelemetryEventsWindowInsightsRequest, options?: RawAxiosRequestConfig): AxiosPromise<TelemetryEventsWindowInsightsDto> {
            return localVarFp.getTelemetryEventsWindowInsights(requestParameters.deviceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDevices(options?: RawAxiosRequestConfig): AxiosPromise<Array<DeviceDto>> {
            return localVarFp.listDevices(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DeviceApiListTelemetryEventsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTelemetryEvents(requestParameters: DeviceApiListTelemetryEventsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<TelemetryEventDto>> {
            return localVarFp.listTelemetryEvents(requestParameters.deviceId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getTelemetryEventsWindowInsights operation in DeviceApi.
 * @export
 * @interface DeviceApiGetTelemetryEventsWindowInsightsRequest
 */
export interface DeviceApiGetTelemetryEventsWindowInsightsRequest {
    /**
     * 
     * @type {string}
     * @memberof DeviceApiGetTelemetryEventsWindowInsights
     */
    readonly deviceId: string
}

/**
 * Request parameters for listTelemetryEvents operation in DeviceApi.
 * @export
 * @interface DeviceApiListTelemetryEventsRequest
 */
export interface DeviceApiListTelemetryEventsRequest {
    /**
     * 
     * @type {string}
     * @memberof DeviceApiListTelemetryEvents
     */
    readonly deviceId: string
}

/**
 * DeviceApi - object-oriented interface
 * @export
 * @class DeviceApi
 * @extends {BaseAPI}
 */
export class DeviceApi extends BaseAPI {
    /**
     * 
     * @param {DeviceApiGetTelemetryEventsWindowInsightsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceApi
     */
    public getTelemetryEventsWindowInsights(requestParameters: DeviceApiGetTelemetryEventsWindowInsightsRequest, options?: RawAxiosRequestConfig) {
        return DeviceApiFp(this.configuration).getTelemetryEventsWindowInsights(requestParameters.deviceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceApi
     */
    public listDevices(options?: RawAxiosRequestConfig) {
        return DeviceApiFp(this.configuration).listDevices(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DeviceApiListTelemetryEventsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeviceApi
     */
    public listTelemetryEvents(requestParameters: DeviceApiListTelemetryEventsRequest, options?: RawAxiosRequestConfig) {
        return DeviceApiFp(this.configuration).listTelemetryEvents(requestParameters.deviceId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TelemetryEventApi - axios parameter creator
 * @export
 */
export const TelemetryEventApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {TelemetryEventDto} [telemetryEventDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTelemetryEvent: async (telemetryEventDto?: TelemetryEventDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/TelemetryEvent`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(telemetryEventDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TelemetryEventApi - functional programming interface
 * @export
 */
export const TelemetryEventApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TelemetryEventApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {TelemetryEventDto} [telemetryEventDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTelemetryEvent(telemetryEventDto?: TelemetryEventDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTelemetryEvent(telemetryEventDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TelemetryEventApi.createTelemetryEvent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TelemetryEventApi - factory interface
 * @export
 */
export const TelemetryEventApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TelemetryEventApiFp(configuration)
    return {
        /**
         * 
         * @param {TelemetryEventApiCreateTelemetryEventRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTelemetryEvent(requestParameters: TelemetryEventApiCreateTelemetryEventRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createTelemetryEvent(requestParameters.telemetryEventDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createTelemetryEvent operation in TelemetryEventApi.
 * @export
 * @interface TelemetryEventApiCreateTelemetryEventRequest
 */
export interface TelemetryEventApiCreateTelemetryEventRequest {
    /**
     * 
     * @type {TelemetryEventDto}
     * @memberof TelemetryEventApiCreateTelemetryEvent
     */
    readonly telemetryEventDto?: TelemetryEventDto
}

/**
 * TelemetryEventApi - object-oriented interface
 * @export
 * @class TelemetryEventApi
 * @extends {BaseAPI}
 */
export class TelemetryEventApi extends BaseAPI {
    /**
     * 
     * @param {TelemetryEventApiCreateTelemetryEventRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TelemetryEventApi
     */
    public createTelemetryEvent(requestParameters: TelemetryEventApiCreateTelemetryEventRequest = {}, options?: RawAxiosRequestConfig) {
        return TelemetryEventApiFp(this.configuration).createTelemetryEvent(requestParameters.telemetryEventDto, options).then((request) => request(this.axios, this.basePath));
    }
}



