<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kallipr.Domain\Kallipr.Domain.csproj" />
    <ProjectReference Include="..\Kallipr.Infrastructure\Kallipr.Infrastructure.csproj" />
  </ItemGroup>

</Project>
